server:
  port: 80
#  servlet:
#    context-path: /bears

managment:
  endpoint:
    web:
      exposure:
        include: "*"

spring:
  datasource:
    username: root
    password: P@ssword2022
    url: jdbc:mysql://35.184.137.230:3306/Users
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

